### ISSUE TITLE
Add License to repository

### ISSUE THREAD

**Issue by IanSaucy** [poke1024/bbz-segment#3]
Hey,

Sorry to create another issue but I figured it was the best way to ask this. I was wondering if you would consider adding a license to the repo on how the code can/cannot be re-used etc.

I'm a personal fan of GPL2(Mainly because it requires keeping any modifications OS as well) and MIT.

Thank you!

**Comment by poke1024** [comment]
Yes, good idea, added a GPL2 license :blush:
